### GET ALL TASKS
GET http://localhost:3000/tasks

### GET ALL TASKS with filters status
GET http://localhost:3000/tasks?status=OPEN

### GET ALL TASKS with both filters
GET http://localhost:3000/tasks?status=OPEN&search=email

### GET TASK By ID
GET http://localhost:3000/tasks/ab67d658-2257-44ae-bfa8-a6709be3d7f6

### POST TASK
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "User name",
  "description": "User email",
  "banana": "User email"
}

### POST TASK
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Breakfast with John",
  "description": "include meat"
}

### Delete TASK By ID
DELETE http://localhost:3000/tasks/2779a139-0152-4628-9801-0e32f60371ae

### Patch TASK By ID
PATCH http://localhost:3000/tasks/15f385c7-4bab-4a12-82b5-417640c3e2d2/status
Content-Type: application/json

{
  "status": "DONE"
}
