### GET ALL TASKS
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW8yIiwiaWF0IjoxNjY2MDY2NjY3LCJleHAiOjE2NjYwNzAyNjd9.SRBm3HAUbsS_Fr_f7ji-MjGAgbM4KdyXXih4t6O3Ytg

### GET ALL TASKS with filters status
GET http://localhost:3000/tasks?status=OPEN
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW8xIiwiaWF0IjoxNjY2MDY1ODQzLCJleHAiOjE2NjYwNjk0NDN9.VHVPo8k41qYhQ8HexMEn6GOL6XG9ErhaF8MjNoQlcf8

### GET ALL TASKS with both filters
GET http://localhost:3000/tasks?status=OPEN&search=email

### GET TASK By ID
GET http://localhost:3000/tasks/f2dd2b2c-af75-4fe6-8964-154610866e78
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW8xIiwiaWF0IjoxNjY2MDY3MzU2LCJleHAiOjE2NjYwNzA5NTZ9.8Mnbh8pKHUD3pt91mzPsFg2GbwjBFsb1xST9-BIvrCk

### POST TASK
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW8yIiwiaWF0IjoxNjY2MDY2NDYwLCJleHAiOjE2NjYwNzAwNjB9.AoMmh3eeW606oEkHUOUkcxSwDNMQE1QNrp3aEcyjbkU

{
  "title": "task for two",
  "description": "task for two",
  "banana": "task for two"
}

### POST TASK
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Breakfast with John",
  "description": "include meat"
}

### Delete TASK By ID
DELETE http://localhost:3000/tasks/2779a139-0152-4628-9801-0e32f60371ae

### Patch TASK By ID
PATCH http://localhost:3000/tasks/15f385c7-4bab-4a12-82b5-417640c3e2d2/status
Content-Type: application/json

{
  "status": "DONE"
}
